[package]
name = "clock"
version = "0.1.0"
authors = ["planet0104 <planet0104@gmail.com>"]

[dependencies]
sdl2-sys = "0.31.0"
time = "0.1"

[dependencies.sdl2]
    version = "0.31"
    default-features = false
    features = ["image", "ttf"]

[lib]
name = "clocklib"
crate-type=["dylib"]